
usnames = [
'John Smith',
'Emily Johnson',
'Michael Brown',
'Olivia Davis',
'William Miller',
'Sophia Wilson',
'James Taylor',
'Ava Martinez',
'Benjamin Anderson',
'Isabella Thomas',
'Daniel Garcia',
'Mia Rodriguez',
'Matthew Hernandez',
'Abigail Lopez',
'David Martin',
'Emma Lee',
'Joseph Gonzalez',
'Harper Perez',
'Christopher White',
'Evelyn Hall',
'Andrew Young',
'Ella King',
'Joshua Scott',
'Avery Adams',
'Ryan Baker',
'Scarlett Green',
'Ethan Allen',
'Chloe Nelson',
'Nicholas Hill',
'Grace Carter',
'Tyler Mitchell',
'Lillian Roberts',
'Brandon Phillips',
'Nora Campbell',
'Jonathan Parker',
'Hazel Evans',
'Samuel Turner',
'Eleanor Collins',
'Christian Stewart',
'Aurora Sanchez',
'Dylan Morris',
'Savannah Reed',
'Zachary Cook',
'Camila Morgan',
'Jose Bell',
'Luna Cooper',
'Kevin Bailey',
'Aaliyah Richardson',
'Caleb Cox',
'Leah Kelly',
'Jason Ward',
]
uscities = [
'New York City, USA',
'Los Angeles, USA',
'Chicago, USA',
'Houston, USA',
'Phoenix, USA',
'Philadelphia, USA',
'San Antonio, USA',
'San Diego, USA',
'Dallas, USA',
'San Jose, USA',
'Austin, USA',
'Jacksonville, USA',
'Fort Worth, USA',
'Columbus, USA',
'Charlotte, USA',
'San Francisco, USA',
'Indianapolis, USA',
'Seattle, USA',
'Denver, USA',
'Washington D.C., USA',
'Boston, USA',
'El Paso, USA',
'Nashville, USA',
'Detroit, USA',
'Oklahoma City, USA',
'Portland, USA',
'Las Vegas, USA',
'Memphis, USA',
'Louisville, USA',
'Baltimore, USA',
'Milwaukee, USA',
'Albuquerque, USA',
'Tucson, USA',
'Fresno, USA',
'Sacramento, USA',
'Mesa, USA',
'Atlanta, USA',
'Kansas City, USA',
'Colorado Springs, USA',
'Miami, USA',
'Raleigh, USA',
'Omaha, USA',
'Long Beach, USA',
'Virginia Beach, USA',
'Oakland, USA',
'Minneapolis, USA',
'Tulsa, USA',
'Arlington, USA',
'New Orleans, USA',
'Wichita, USA'
]
indiannames =[
'Rahul Sharma',
'Priya Patel',
'Amit Kumar',
'Neha Singh',
'Rajesh Gupta',
'Anjali Verma',
'Vijay Singh',
'Aishwarya Reddy',
'Sanjay Yadav',
'Riya Sharma',
'Deepak Patel',
'Simran Kaur',
'Ajay Kumar',
'Pooja Gupta',
'Suresh Reddy',
'Kavita Singh',
'Anil Yadav',
'Nisha Verma',
'Mahesh Sharma',
'Priya Patel',
'Ramesh Kumar',
'Anika Singh',
'Dinesh Gupta',
'Isha Reddy',
'Pradeep Yadav',
'Mansi Sharma',
'Vikram Patel',
'Ananya Kumar',
'Sachin Singh',
'Diya Gupta',
'Nitin Reddy',
'Shreya Yadav',
'Arun Sharma',
'Tanya Verma',
'Girish Patel',
'Riya Kumar',
'Manoj Singh',
'Sanjana Gupta',
'Praveen Reddy',
'Neha Yadav',
'Mukesh Sharma',
'Alia Verma',
'Sandeep Patel',
'Disha Kumar',
'Rajiv Singh',
'Trisha Gupta',
'Vinay Reddy',
'Anushka Yadav',
'Harish Sharma',
'Meera Verma'
]
indiancities = [
'Mumbai, India',
'Delhi, India',
'Bangalore, India',
'Hyderabad, India',
'Ahmedabad, India',
'Chennai, India',
'Kolkata, India',
'Surat, India',
'Pune, India',
'Jaipur, India',
'Lucknow, India',
'Kanpur, India',
'Nagpur, India',
'Indore, India',
'Thane, India',
'Bhopal, India',
'Visakhapatnam, India',
'Pimpri-Chinchwad, India',
'Patna, India',
'Vadodara, India',
'Ghaziabad, India',
'Ludhiana, India',
'Agra, India',
'Nashik, India',
'Faridabad, India',
'Meerut, India',
'Rajkot, India',
'Kalyan-Dombivli, India',
'Vasai-Virar, India',
'Varanasi, India',
'Srinagar, India',
'Aurangabad, India',
'Dhanbad, India',
'Amritsar, India',
'Navi Mumbai, India',
'Allahabad, India',
'Howrah, India',
'Ranchi, India',
'Gwalior, India',
'Jabalpur, India',
'Coimbatore, India',
'Vijayawada, India',
'Jodhpur, India',
'Madurai, India',
'Raipur, India',
'Kota, India',
'Guwahati, India',
'Chandigarh, India',
'Solapur, India',
'Hubli-Dharwad, India',
]